// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk5jOVtF8R1cnwUATsHJhQgxasPLZvfZE',
    appId: '1:93145446085:web:7d45cae58a0672d17f22ac',
    messagingSenderId: '93145446085',
    projectId: 'shopsmart-47282',
    authDomain: 'shopsmart-47282.firebaseapp.com',
    storageBucket: 'shopsmart-47282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0gDSJbeoYxOSehGBb4_z4iwdZEkDY4Y',
    appId: '1:93145446085:android:fe4dde65248b43587f22ac',
    messagingSenderId: '93145446085',
    projectId: 'shopsmart-47282',
    storageBucket: 'shopsmart-47282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgoWtxeNaHt7Tx6DK_cicf7s7M0wt2Fo',
    appId: '1:93145446085:ios:895fec1bba11a0557f22ac',
    messagingSenderId: '93145446085',
    projectId: 'shopsmart-47282',
    storageBucket: 'shopsmart-47282.appspot.com',
    iosBundleId: 'com.example.shopsmartAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYgoWtxeNaHt7Tx6DK_cicf7s7M0wt2Fo',
    appId: '1:93145446085:ios:895fec1bba11a0557f22ac',
    messagingSenderId: '93145446085',
    projectId: 'shopsmart-47282',
    storageBucket: 'shopsmart-47282.appspot.com',
    iosBundleId: 'com.example.shopsmartAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk5jOVtF8R1cnwUATsHJhQgxasPLZvfZE',
    appId: '1:93145446085:web:e2384905e0df78177f22ac',
    messagingSenderId: '93145446085',
    projectId: 'shopsmart-47282',
    authDomain: 'shopsmart-47282.firebaseapp.com',
    storageBucket: 'shopsmart-47282.appspot.com',
  );
}
